Repository niji-co/Fusion-Server, pull requests merged in 2021-05, with the labels that each got.

#3 Set up base project
  .gitignore
  .vscode/settings.json
  README.md
  manage.py
  web_project/__init__.py
  web_project/asgi.py
  web_project/settings.py
  web_project/urls.py
  web_project/wsgi.py
Labels: Status: Revision Needed, Type: Enhancement

#7 fix(security): move secret key to config
  .gitignore
  web_project/settings.py
Labels: Status: Accepted, Type: Vulnerability

#8 feat: Basic Mongo CRUD Operations
  .vscode/settings.json
  tests/test_insert_new_project.py
  tests/test_project_deletion.py
  tests/test_update_project_info.py
  tests/test_update_user_info.py
  tests/test_user_search.py
  web_project/db.py
Labels: Status: Accepted, Type: Enhancement

#10 style: adopt PEP 8's style guidelines
  tests/test_connection.py
  tests/test_insert_new_project.py
  tests/test_project_deletion.py
  tests/test_update_project_info.py
  tests/test_update_user_info.py
  tests/test_user_search.py
  web_project/db.py
Labels: Status: Review Needed, Type: Enhancement
